### ISSUE TITLE
[Bug]: env json not readable

### ISSUE THREAD

**Issue by vwasteels** [jekuer/directus-extension-system-email-i18n#3]
### What happened?

Hello,

Thanks for this plugin !

I have an issue with the .env config, when I put : 
```
I18N_EMAIL_SUBJECTS={"fr":{"user-registration":"Confirmation de votre email"}}
```

and try to register a new user, I get this error in the log : 

```
[08:17:24.862] ERROR: Could not send email verification mail
    err: {
      "type": "SyntaxError",
      "message": "Unexpected token u in JSON at position 0",
      "stack":
          SyntaxError: Unexpected token u in JSON at position 0
              at JSON.parse (<anonymous>)
              at file:///directus/extensions/directus-extension-system-email-i18n/dist/index.js?t=1738770954678:1:65027
              at Emitter.emitFilter (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/emitter.js:36:38)
              at MailService.send (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/services/mail/index.js:39:39)
              at UsersService.registerUser (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/services/users.js:394:18)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.50_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.6.2___e_2e2it2zjrr5xglt6v6r5creice/node_modules/@directus/api/dist/controllers/users.js:315:5
    }
```

Is there anything to know about the format ?

Thank you,
Vincent

### Directus type and version

Docker installation
version : 11.1.1

my docker-compose.yml :

```yml
version: '3.8'

x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

volumes:
  directus-uploads:
    driver: local
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local

services:

  directus:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-image
    <<: *x-logging
    restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      - directus-uploads:/directus/uploads
      - ./directus-ext/bundle:/directus/extensions/directus-extension-bundle:ro
      - ./directus-migrations:/directus/migrations:ro
    environment:
      TZ: "${TIMEZONE}"
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      LOG_LEVEL: "${DIRECTUS_LOG_LEVEL}"
      PUBLIC_URL: "${DIRECTUS_PUBLIC_URL}"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "${POSTGRES_DB}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      EMAIL_SMTP_HOST: "${SMTP_HOST}"
      EMAIL_SMTP_PORT: "${SMTP_PORT}"
      EMAIL_SMTP_USER: "${SMTP_USER}"
      EMAIL_SMTP_PASSWORD: "${SMTP_PASS}"
      EMAIL_SMTP_SECURE: "${SMTP_SSL}"
      EMAIL_SMTP_NAME: "${SMTP_SERVER_NAME}"
      EMAIL_FROM: "${SMTP_SENDER}"
      EMAIL_TRANSPORT: "smtp"
      WEBSOCKETS_ENABLED: "true"
      EXTENSIONS_AUTO_RELOAD: "true"
      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "memory"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "${DIRECTUS_CORS_ORIGIN}"
      CORS_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      CORS_ALLOWED_HEADERS: "*, Authorization, Content-type"
      CORS_CREDENTIALS: "true"
      CORS_MAX_AGES: "600"
      I18N_EMAIL_SUBJECTS: ${I18N_EMAIL_SUBJECTS}
    depends_on:
      - postgres
      - mailhog

  postgres:
    image: postgis/postgis:15-3.4-alpine
    <<: *x-logging
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"

  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    <<: *x-logging
    ports:
      - "5555:5555"
    environment:
      POSTGRES_DATABASE: "${POSTGRES_DB}"
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "5432"
      POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.3
    restart: unless-stopped
    <<: *x-logging
    ports:
      - "5556:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    <<: *x-logging
    ports:
      - "8025:8025"
      - "1025"

```

and Dockerfile :

```
FROM node:20-alpine as third-party-ext
WORKDIR /extensions
ADD directus-ext/third-party .
RUN npm install
# Move all extensions the starts with directus-extension-, using find, to the /extensions/directus folder
RUN mkdir -p ./directus
RUN cd node_modules && find . -maxdepth 1 -type d -name "directus-extension-*" -exec mv {} ../directus \;

FROM directus/directus:11.1.1 as dev-image
# Copy third party extensions
COPY --from=third-party-ext /extensions/directus ./extensions

FROM node:20 as custom-ext
WORKDIR /extensions
# Add all extensions here
ADD directus-ext/bundle ./bundle
# Build extensions one by one
RUN cd bundle && npm install && npm run build
## Clean up
RUN rm -rf ./bundle/node_modules

FROM node:20 as custom-ext
WORKDIR /extensions
# Add all extensions here
ADD directus-ext/bundle ./bundle
# Build extensions one by one
RUN cd bundle && npm install && npm run build
## Clean up
RUN rm -rf ./bundle/node_modules

FROM dev-image as prod-image
# Copy customizations
ADD directus-migrations ./migrations
# Copy custom extensions
COPY --from=custom-ext /extensions/bundle ./extensions/directus-extension-bundle

# Fix for Digital Ocean App Platform
FROM prod-image as digital-ocean
USER root
RUN chown -R node:node ./extensions
RUN apk --no-cache add procps
USER node
ENV PIDUSAGE_USE_PS=true
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
```
